### ISSUE TITLE
Umožnit mít v brandingu odkaz na homepage

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/gov-design-system#11]
V brandingu nejde udělat odkaz, co by vedl na home. Když do `h1` dám `&lt;a href ...` tak místo odkazu ten text prostě zmizí.

**Comment by skodapetr** [comment]
On tam byl, ale odkaz defaultně používá barvu stejnou barvu, jaká je použitá pro hlavičku. 
```
    <gov-branding>
      <h1> <a href="#">Portál o datech</a> </h1>
 ...
```
By teď mělo zobrazit odkaz jako text.

**Comment by jakubklimek** [comment]
Je tam, ale pořád špatně obarvený.
K tomu jen jedná přístupnostní poznámka - je lepší když ten branding text není nadpis (h1-h6), protože skutečný nadpis (h1) stránky je na všech kromě homepage jinde - tedy kdyby to šlo třeba jako span, bylo by to ideální
