### ISSUE TITLE
Definiční list není nastylován

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/gov-design-system#12]
Není nastylovaný definiční list, viz https://oha02.dia.gov.cz/dokumenty/vzorová-směrnice-pro-subjekty-s-podřízenými-organizacemi/#pojmy

**Comment by skodapetr** [comment]
Přidal jsem, zatím dočasně, do critical.css. 
Bootstrap využívá https://getbootstrap.com/docs/4.0/content/reboot/ což je vlastně takový rozumný základ pro výchozí zobrazení. Knihovny často používají nějakou "reset"-like knihovnu, která sjednotí výchozí vizuální styl skrze prohlížeče. 

Zařazení takové knihovny, a zejména analýza dopadů takové akce, je ale mimo toto issue.
