### ISSUE TITLE
Add support for adjusting positions of blocks (headings, buttons)

### ISSUE THREAD

**Issue by jakubklimek** [datagov-cz/gov-design-system#15]
Support for allowing users to e.g. place a button to the right instead of the default left is currently missing.

**Comment by skodapetr** [comment]
Can you provide an example?

**Comment by jakubklimek** [comment]
One example is the "News" button e.g. [here](https://oha02.dia.gov.cz/#novinky-ze-světa-dat-veřejné-správy) but that is now solved using `flex-justify-end`. So I think this is it.
