### ISSUE TITLE
Stejná výška pro gov-card v gov-tile

### ISSUE THREAD

**Issue by skodapetr** [datagov-cz/gov-design-system#2]
Cílem je mít gov-cad v gov-tile tak aby měli všechny stejnou velikost a bylo tak možné patičku.
![image](https://github.com/datagov-cz/design-system/assets/3341693/90369e90-a07c-4703-9c97-186e0b70fd4f)

**Comment by jakubklimek** [comment]
[tiles](https://oha02.dia.gov.cz/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/co-jsou-otev%C5%99en%C3%A1-data/) - jsou stejně velké, ale nelze mít rozumně tlačítka. Jen jeden odkaz, nebo nic.
![image](https://github.com/datagov-cz/design-system/assets/718827/ee81df49-7488-46fa-b4d2-5289695a0491)

[kartičky v tiles](https://oha02.dia.gov.cz/vzd%C4%9Bl%C3%A1v%C3%A1n%C3%AD/e-learning/katalogizace-otev%C5%99en%C3%BDch-dat/) - lze mít tlačítka v patičce, ale nejsou stejně velké
![image](https://github.com/datagov-cz/design-system/assets/718827/80d69a8e-d30e-45bb-a80a-5cff1ad8ac45)

**Comment by skodapetr** [comment]
Nově přidáno `gutter-x`, `gutter-y` a `full-height`. Příklad použití níže:
```
<gov-grid gutter-x="1.5rem" gutter-y="1.5rem">
  <gov-grid-item size="3/12">
    <gov-card label="Co jsou otevřená data" full-height>
      <p>
        Cílem školení je poskytnou  ...
      </p>
      <div slot="footer">
        <gov-icon type="complex" name="time"></gov-icon> 3,5 hodiny
      </div>
    </gov-card>
  </gov-grid-item>
</gov-grid>
```
Co chybí oproti tiles je pak možnost kliknutí na card.

**Comment by jakubklimek** [comment]
Ještě to asi uplně správně nefunguje:
![image](https://github.com/datagov-cz/design-system/assets/718827/b7e2ffad-b04e-4162-88d0-a366293fc218)
